# Generated by Django 2.0.13 on 2019-03-12 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='phase',
            name='name_phase',
            field=models.CharField(default='Unnamed Phase', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='name_proj',
            field=models.CharField(default='Unnamed Project', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='name_task',
            field=models.CharField(default='Unnamed Task', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='architect_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.Architect'),
        ),
    ]
