# Generated by Django 2.0.13 on 2019-03-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_auto_20190311_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='project_manager.Project'),
        ),
    ]
