# Generated by Django 2.0.13 on 2019-03-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_auto_20190316_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='phase_id',
            new_name='phase',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
    ]
